In [1]:
import nibabel as nib
import numpy as np
import os
import glob
import SimpleITK as sitk

In [4]:
image = nib.load("G:\Semester 5\Data Science and Engineering Project\Codes\MRI-slices-super-resolution-V2\data-processing\data\downsampled_updated_CC0001_philips_15_55_M.nii.gz")
print(image.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 175 256 256   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1. 1. 1. 1. 0. 0. 0. 0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -96.71713
qoffset_y       : -117.40074
qoffset_z       : -113.47519
srow_x          : [  1.        0.

In [5]:
new_img = image.slicer[::5, :, :]
print(new_img.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3  35 256 256   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1. 5. 1. 1. 1. 1. 1. 1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -96.71713
qoffset_y       : -117.40074
qoffset_z       : -113.47519
srow_x          : [  5.        0.

In [8]:
# Save new image
nib.save(new_img, "G:\Semester 5\Data Science and Engineering Project\Codes\MRI-slices-super-resolution-V2\data-processing\data\/new_downsampled_updated_CC0001_philips_15_55_M_5.nii.gz")

In [9]:
# load the image
img = nib.load("G:\Semester 5\Data Science and Engineering Project\Codes\MRI-slices-super-resolution-V2\data-processing\data\/new_downsampled_updated_CC0001_philips_15_55_M_5.nii.gz")
print(img.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3  35 256 256   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1. 5. 1. 1. 1. 1. 1. 1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -96.71713
qoffset_y       : -117.40074
qoffset_z       : -113.47519
srow_x          : [  5.        0.

In [10]:
base_dir = r"G:\Semester 5\Data Science and Engineering Project\Codes\MRI-Enhance-3D\DataSet"

# Use glob to find all files in the directory
file_paths = glob.glob(os.path.join(base_dir, '*'))

In [11]:
def read_nifti_file(filepath, save_header=False):
    # Extract the file name from the file path
    file_name = os.path.basename(filepath)

    # Read the .nii file
    img = nib.load(filepath)

    # Extract header data
    header = img.header

    # Extract image data
    data = img.get_fdata()

    # Save the header data if specified
    if save_header:
        with open('./data/' + file_name + '.txt', 'w') as file:
            file.write(str(header))
    
    return img, header, data, file_name


In [12]:
# Test1
image, header, data, file_name = read_nifti_file(file_paths[1], save_header=True)

In [13]:
type(image)

nibabel.nifti1.Nifti1Image

In [14]:
def get_header_dims(file_paths):
    header_dims = []
    for file_path in file_paths:
        header = read_nifti_file(file_path, save_header=False)[1]['dim']
        header_dims.append(header)
    return header_dims

In [15]:
header_dims = get_header_dims(file_paths)

In [16]:
unique_headers = list(set([str(header) for header in header_dims]))
print(len(unique_headers))
unique_headers

37


['[  3 160 288 288   1   0   0   0]',
 '[  3 256 204 256   1   0   0   0]',
 '[  3 180 240 240   1   0   0   0]',
 '[  3 184 256 256   1   0   0   0]',
 '[  3 256 168 256   1   0   0   0]',
 '[  3 161 288 288   1   0   0   0]',
 '[  3 171 288 288   1   0   0   0]',
 '[  3 179 288 288   1   0   0   0]',
 '[  3 162 288 288   1   0   0   0]',
 '[  3 158 288 288   1   0   0   0]',
 '[  3 200 256 256   1   0   0   0]',
 '[  3 256 174 256   1   0   0   0]',
 '[  3 176 288 288   1   0   0   0]',
 '[  3 172 256 256   1   0   0   0]',
 '[  3 150 288 288   1   0   0   0]',
 '[  3 157 288 288   1   0   0   0]',
 '[  3 256 186 256   1   0   0   0]',
 '[  3 170 288 288   1   0   0   0]',
 '[  3 168 288 288   1   0   0   0]',
 '[  3 164 288 288   1   0   0   0]',
 '[  3 256 196 256   1   0   0   0]',
 '[  3 154 288 288   1   0   0   0]',
 '[  3 256 192 256   1   0   0   0]',
 '[  3 156 288 288   1   0   0   0]',
 '[  3 256 200 256   1   0   0   0]',
 '[  3 192 256 256   1   0   0   0]',
 '[  3 176 2

In [17]:
# finding minimum and maximum values of each dimension
min_dim = [1000,1000,1000]
max_dim = [0,0,0]
for header in header_dims:
    for i in range(3):
        if header[i+1] < min_dim[i]:
            min_dim[i] = header[i+1]
        if header[i+1] > max_dim[i]:
            max_dim[i] = header[i+1]

min_dim, max_dim

([150, 168, 224], [256, 288, 288])

In [18]:
import nibabel as nib
import numpy as np
import torch
from monai.transforms import Resize

In [19]:
# Function to resample NIfTI image and update the header and affine matrix
def resample_nifti_monai_with_affine(nifti_file, new_shape):
    # Load the NIfTI image
    img = nib.load(nifti_file)
    data = img.get_fdata()
    original_shape = data.shape
    original_affine = img.affine
    print(original_shape)
    print(original_affine)

    # Create a tensor from the image data and add batch and channel dimensions
    data_tensor = torch.tensor(data, dtype=torch.float32).unsqueeze(0)

    # Define the MONAI Resize transform
    resize_transform = Resize(spatial_size=new_shape, mode='area')  # mode='area' for downsampling

    # Apply the transform to resample the image
    resampled_tensor = resize_transform(data_tensor)

    # Remove extra dimensions to get the resampled data
    resampled_data = resampled_tensor.squeeze().numpy()

    # Compute the scaling factors based on the old and new shapes
    scaling_factors = np.array(original_shape) / np.array(new_shape)

    # Update the affine matrix by adjusting the voxel size (scaling)
    new_affine = original_affine.copy()
    for i in range(3):  # Only scale the spatial dimensions (x, y, z)
        new_affine[i, i] *= scaling_factors[i]

    # Create a new NIfTI image with the resampled data and the new affine matrix
    resampled_img = nib.Nifti1Image(resampled_data, new_affine, header=img.header)

    # Update the header to reflect the new voxel sizes (pixel dimensions)
    # The voxel size is stored in the header's `pixdim` field
    new_voxel_sizes = np.array(img.header.get_zooms()) * scaling_factors
    resampled_img.header.set_zooms(new_voxel_sizes)

    return resampled_img

In [22]:
import nibabel as nib
import numpy as np
from scipy.ndimage import zoom

# Function to resample NIfTI image to a fixed shape
def resample_nifti(nifti_file, new_shape):
    # Load NIfTI image
    img = nib.load(nifti_file)
    data = img.get_fdata()
    
    # Original shape and voxel dimensions
    original_shape = data.shape
    original_affine = img.affine
    
    # Calculate the rescaling factors for each dimension
    scaling_factors = [new_dim / old_dim for new_dim, old_dim in zip(new_shape, original_shape)]
    
    # Resample the image data to the new shape
    resampled_data = zoom(data, scaling_factors, order=1)  # 'order=1' for linear interpolation
    
    # Create new affine by scaling the voxel sizes
    new_affine = original_affine.copy()
    new_affine[:3, :3] *= np.array([original_shape[i] / new_shape[i] for i in range(3)])
    
    # Create new NIfTI image with resampled data and updated affine
    resampled_img = nib.Nifti1Image(resampled_data, new_affine)
    
    return resampled_img

In [24]:
resampled_img2 = resample_nifti(file_paths[1], (150, 256, 256))
nib.save(resampled_img2, 'resampled_image2.nii.gz')

In [20]:
resampled_monai = resample_nifti_monai_with_affine(file_paths[0], new_shape=(150, 256, 256))

# Save the resampled image
nib.save(resampled_monai, 'resampled_monai.nii.gz')

(171, 256, 256)
[[ 9.95842218e-01  6.39259815e-02  6.48697987e-02 -9.67171326e+01]
 [-6.38532937e-02  9.97954190e-01 -3.19350394e-03 -1.17400742e+02]
 [-6.49411157e-02 -9.61925660e-04  9.97888625e-01 -1.13475189e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [21]:
resampled_img = resample_nifti_monai_with_affine(file_paths[0], new_shape=(150, 200, 200))
nib.save(resampled_img, 'resampled_img.nii.gz')

(171, 256, 256)
[[ 9.95842218e-01  6.39259815e-02  6.48697987e-02 -9.67171326e+01]
 [-6.38532937e-02  9.97954190e-01 -3.19350394e-03 -1.17400742e+02]
 [-6.49411157e-02 -9.61925660e-04  9.97888625e-01 -1.13475189e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [73]:
import tabulate

img = nib.load(file_paths[0])

header_original = img.header.structarr
header_monai_sampled = resampled_img.header.structarr

header_params = img.header.keys()

compare = []
for param in header_params:
    compare.append([param, header_original[param].tolist(), header_monai_sampled[param].tolist()])

table = tabulate.tabulate(compare, tablefmt='html')

table

'<table>\n<tbody>\n<tr><td>sizeof_hdr    </td><td>348                                                                                    </td><td>348                                                                                    </td></tr>\n<tr><td>data_type     </td><td>b&#x27;&#x27;                                                                                    </td><td>b&#x27;&#x27;                                                                                    </td></tr>\n<tr><td>db_name       </td><td>b&#x27;&#x27;                                                                                    </td><td>b&#x27;&#x27;                                                                                    </td></tr>\n<tr><td>extents       </td><td>0                                                                                      </td><td>0                                                                                      </td></tr>\n<tr><td>session_error </td><td>0                                                                                      </td><td>0                                                                                      </td></tr>\n<tr><td>regular       </td><td>b&#x27;r&#x27;                                                                                   </td><td>b&#x27;r&#x27;                                                                                   </td></tr>\n<tr><td>dim_info      </td><td>0                                                                                      </td><td>0                                                                                      </td></tr>\n<tr><td>dim           </td><td>[3, 171, 256, 256, 1, 0, 0, 0]                                                         </td><td>[3, 150, 200, 200, 1, 1, 1, 1]                                                         </td></tr>\n<tr><td>intent_p1     </td><td>0.0                                                                                    </td><td>0.0                                                                                    </td></tr>\n<tr><td>intent_p2     </td><td>0.0                                                                                    </td><td>0.0                                                                                    </td></tr>\n<tr><td>intent_p3     </td><td>0.0                                                                                    </td><td>0.0                                                                                    </td></tr>\n<tr><td>intent_code   </td><td>0                                                                                      </td><td>0                                                                                      </td></tr>\n<tr><td>datatype      </td><td>4                                                                                      </td><td>4                                                                                      </td></tr>\n<tr><td>bitpix        </td><td>16                                                                                     </td><td>16                                                                                     </td></tr>\n<tr><td>slice_start   </td><td>0                                                                                      </td><td>0                                                                                      </td></tr>\n<tr><td>pixdim        </td><td>[1.0, 0.9999982118606567, 1.0, 1.0, 0.007143000140786171, 0.0, 0.0, 0.0]               </td><td>[1.0, 1.139997959136963, 1.2799999713897705, 1.2799999713897705, 1.0, 1.0, 1.0, 1.0]   </td></tr>\n<tr><td>vox_offset    </td><td>0.0                                                                                    </td><td>0.0                                                                                    </td></tr>\n<tr><td>scl_slope     </td><td>nan                                             

In [74]:
def overide_header(img, header):
    voxel_spacing = header.get_zooms()

    qoffset_x = header['qoffset_x']
    qoffset_y = header['qoffset_y']
    qoffset_z = header['qoffset_z']

    new_affine = np.array([
        [voxel_spacing[0], 0, 0, qoffset_x],
        [0, voxel_spacing[1], 0, qoffset_y],
        [0, 0, voxel_spacing[2], qoffset_z],
        [0, 0, 0, 1]
    ])

    new_header = header.copy()
    
    new_header['srow_x'] = new_affine[0,:]
    new_header['srow_y'] = new_affine[1,:]
    new_header['srow_z'] = new_affine[2,:]

    new_image = nib.Nifti1Image(img.get_fdata(), new_affine, new_header)

    return new_image

In [75]:
updated_image = overide_header(resampled_img, resampled_img.header)

In [76]:
print(updated_image.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 150 200 200   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.       1.139998 1.28     1.28     1.       1.       1.       1.      ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'TE=3.2;Time=175927.760'
aux_file        : b'imgComments'
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.00043662597
quatern_c       : 0.026959036
quatern_d       : -0.026536562
qoffset_x     

In [77]:
def downsample_image(img):
    return img.slicer[::5, :, :]

In [78]:
downsampled_image = downsample_image(updated_image)

In [79]:
print(downsampled_image.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3  30 200 200   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.      5.69999 1.28    1.28    1.      1.      1.      1.     ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'TE=3.2;Time=175927.760'
aux_file        : b'imgComments'
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : -96.71713
qoffset_y       : -11

In [82]:
def convert_voxel(img, file_name, new_spacing=[1, 1, 1]):
    interpolator = sitk.sitkLinear

    img_data = img.get_fdata()

    volume = sitk.GetImageFromArray(img_data.astype(np.float32))

    old_spacing = volume.GetSpacing()
    old_size = volume.GetSize()

    new_size = [int(round(osz*ospc/nspc)) for osz, ospc, nspc in zip(old_size, old_spacing, new_spacing)]
    resample_volume = sitk.Resample(volume, new_size, sitk.Transform(), interpolator, volume.GetOrigin(), new_spacing, volume.GetDirection(), 0.0, volume.GetPixelID())

    sitk.WriteImage(resample_volume, f"{file_name}_resampled.nii.gz")

In [83]:
convert_voxel(downsampled_image, file_name)

In [85]:
downsampled_image = nib.load(f"{file_name}_resampled.nii.gz")
print(downsampled_image.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 200 200  30   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [1. 1. 1. 1. 0. 0. 0. 0.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : scanner
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 1.0
qoffset_x       : -0.0
qoffset_y       : -0.0
qoffset_z       : 0.0
srow_x          : [-1.  0.  0. -0.]
srow_y         